# Generated by Django 4.1 on 2022-08-23 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system_users', '0001_initial'),
        ('base', '0001_initial'),
        ('Faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headofdepartment',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_users.suser'),
        ),
        migrations.AddField(
            model_name='headofdepartment',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.state'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.state'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Faculty.faculty'),
        ),
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.state'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Faculty.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Faculty.programme'),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.state'),
        ),
    ]
