# Generated by Django 4.1 on 2022-08-23 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system_users', '0001_initial'),
        ('base', '0001_initial'),
        ('Records', '0001_initial'),
        ('Faculty', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultslip',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_users.suser'),
        ),
        migrations.AddField(
            model_name='resultslip',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Faculty.unit'),
        ),
        migrations.AddField(
            model_name='grade',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.state'),
        ),
        migrations.AddField(
            model_name='distinction',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.state'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Faculty.course'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='distinction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Records.distinction'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.state'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_users.suser'),
        ),
    ]
